### ISSUE TITLE
Could I enable the gatewayAPI feauther?

### ISSUE THREAD

**Issue by peter-hst** [gardener/gardener-extension-networking-cilium#257]
I want to using the [GatwwayAPI](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#gs-gateway-api) with cilium CNI, Do we already support it? Thanks a lot!

I have already updated the `Shoot` resource configuration below
```yaml
  networking:
    type: cilium
    providerConfig:
      apiVersion: cilium.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      hubble:
        enabled: true
      tunnel: geneve
      bpfSocketLBHostnsOnly:
        enabled: true
      overlay:
        enabled: true
```
