### ISSUE TITLE
Image vector overwrite of the `certgen` image leads to ManagedResource that fails to be applied

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-networking-cilium#49]
/area networking
/kind bug
/priority 3

**What happened**:
The Job `spec.template` filed is immutable by design. Currently the extension allows the image of the `hubble-generate-certs` to be overwritten with image vector overwrite.

https://github.com/gardener/gardener-extension-networking-cilium/blob/ccb86f1943552d3c849c2b3cb0be1ae8586df704/charts/internal/cilium/charts/hubble-relay/templates/job.yaml#L19-L20

However change in the `spec.template` of a Job is not allowed, hence the Job fails to be applied.

To workaround this issue I think that networking-cilium extension can:
- use the `resources.gardener.cloud/delete-on-invalid-update` annotation that will delete the Job and create a new one with the new image
- or to switch from Job to something else
- ...

**What you expected to happen**:
Update of the networking-cilium image vector overwrite` should not lead to ManagedResource that fails to be applied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with cilium and hubble enabled:

```yaml
  networking:
    providerConfig:
      apiVersion: cilium.networking.extensions.gardener.cloud/v1alpha1
      hubble:
        enabled: true
      kind: NetworkConfig
    type: cilium
    pods: 10.223.128.0/17
    nodes: 10.222.0.0/16
    services: 10.223.0.0/17
```

2. Update the networking-cilium ctrlreg with imageVectorOverwrite to overwrite for the job image

```yaml
      values:
        imageVectorOverwrite: |
          images:
          - name: certgen
            repository: quay.io/cilium/certgen
            tag: v0.1.2
```

3. Make sure that the corresponding MR cannot be applied

```
$ k -n shoot--foo--bar get mr extension-networking-cilium-config
NAME                                 CLASS   APPLIED   HEALTHY   AGE
extension-networking-cilium-config           False     True      79m
```

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.5.0
- Kubernetes version (use `kubectl version`): v1.19.9
- Cloud provider or hardware configuration:
- Others:
