### ISSUE TITLE
Allow enabling egress gateway feature

### ISSUE THREAD

**Issue by jastBytes** [gardener/gardener-extension-networking-cilium#98]
**How to categorize this issue?**
/area networking
/kind enhancement

**What would you like to be added**:

Cilium introduced the Egress Gateway feature in v1.10 (see the [docs](https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/)). The egress gateway allows users to redirect egress pod traffic through specific, gateway nodes. Packets are masqueraded to the gateway node IP. To make use of this feature with gardener this must be set on the configmap for cilium:

```yaml
enable-ipv4-egress-gateway: true
enable-bpf-masquerade: true
kube-proxy-replacement: strict
```

**Why is this needed**:

For some of our services running in K8s it is necessary to have a single egress IP since the external service ties sessions to IP addresses.
